### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by mwolff65** [klein0r/ioBroker.birthdays#80] opened 2022-04-05 06:25 UTC
### The problem

If birthdays are entered manually in the corresponding tab, no year (year of birth) can be entered directly. At that moment, the [Close] closing fields become invalid and can no longer be used. A birth year input is only possible via the small bigger and smaller arrows behind the year number.

### Version of nodejs

14.18.2

### Version of ioBroker js-controller

3.3.22

### Version of Adapter

1.2.0

### Operating system running ioBroker

Linux Ubuntu 21.04

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment] 2022-04-05 12:01
Duplicate of #78

**Closed by klein0r** 2022-04-05 12:01 UTC
Labels: bug
